/* ------------------------------------------------------------------------
- MAGNITUDE ANALYSIS
- MEASURE DATA AND ORGANIZE RESULTS BY DEFINED DIMENSIONS
- ANALYZE THE DISTRIBUTION OF DATA ACROSS CATEGORIES

FUNCTIONS USED
	- AGGREGATE FUNCTIONS: SUM(), AVG(), COUNT()
	- GROUP BY, ORDER BY
---------------------------------------------------------------------------- */


-- Find total customers by countries
SElECT COUNT(customer_id) AS Total_Customers,
country AS Country
FROM gold.dim_customers
GROUP BY country
ORDER BY Total_Customers DESC

-- Find total customers by gender
SELECT COUNT(customer_id) AS Total_Customers,
gender AS Gender
FROM gold.dim_customers
GROUP BY gender
OrDER BY Total_Customers DESC

-- Find total products by category
SELECT COUNT(DISTINCT product_id) AS Total_Products,
category AS Category
FROM gold.dim_products
GROUP BY category
OrDER BY Total_Products DESC

-- What is the average costs in each category?
SELECT AVG(cost) AS Average_Cost,
category AS Category
FROM gold.dim_products
GROUP BY category
ORDER BY Average_Cost DESC

-- What is the total revenue generated for each category?
SELECT 
p.category,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Find total revenue is generated by each customer?
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT 
c.country,
SUM(f.quantity) total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.country
ORDER BY total_sold_items DESC